### ISSUE TITLE
Opening a modal dialog in a JS function generates a SyntaxError: return not in function

### ISSUE THREAD

**Issue by terrettazmaxime** [niutech/showModalDialog#34]
Is there a way to use this polyfill inside a JS function ?
I have created a modified demo to explain the current issue. (Button 3)

[Modified-Demo.zip](https://github.com/niutech/showModalDialog/files/1488884/Modified-Demo.zip)

**Comment by niutech** [comment]
The problem is when using `eval()`, the statements starting with `showModalDialog()` are being enclosed with brackets, so the `eval`ed code looks like: `{ return "some return value"; }`, which throws an error because this is not a function. The simplest solution is to use the generators, which are supported in [majority of browsers](https://caniuse.com/es6-generators): https://repl.it/repls/CanineUglyIvorygull
